---
title: "Cytation data assembly"
output: 
    html_notebook:
        self_contained: yes
author: "Darren R Tyson"
date: "2020-09-24"
---
#### Assembling cell count data from py-seg-processed images
Cell (nuclear) counts were obtained from images generated by Clayton Wandishin on Cytation 5 in HTS (VAPR) core (2020-09-17). Images were processed using `py-seg` on `ccsb-tempo` server as described in `ccsb-tempo:/home/darren/HTS_segmentation/2020-09-17_Cytation_processing.ipynb`

```{r Setup}
library(diprate)
```


```{r}
d <- read.csv("../data/20200917_Cytation_data.csv", as.is=TRUE)
a <- read.csv('../data/H1048 Luminescence Raw/H1048_AZD-1152_RawLum.csv', as.is=TRUE, row.names = 1)
```

```{r}
d <- addMapInfo(d,"../data/20200917_Cytation_platemap.tsv")
d$uid <- paste(d$plate_id,d$well,sep="_")
d$cell.count <- d$cell_count
d$time_i <- sapply(strsplit(d$file_name,'\\.tif'), "[[", 1)
d$time_i <- as.numeric(sapply(d$time_i, function(x) substr(x,nchar(x)-2,nchar(x))))
d$time <- a$TotHour[d$time_i]
```

```{r Save complete dataset}
full_fn <- "../data/20200917_Cytation_data_with_drugs.csv"
if(!file.exists(full_fn)) write.csv(d, file=full_fn, row.names=FALSE)
```


```{r}
temp <- d[d$cell.line=="DMS53" & d$drug1=="SNS-314",]
id <- unique(temp$uid)
plot(log2(cell.count - ch2_pos) ~ time, data=temp, main="DMS53+SNS-314", type='n')
for(i in id)
{
    dtp <- temp[temp$uid==i,]
    lines(dtp$time,log2(dtp$cell_count-dtp$ch2_pos))
}
```

```{r}
temp <- d[d$cell.line=="DMS53" & d$drug1=="SNS-314",]
id <- unique(temp$uid)
plot(log2(cell.count) ~ time, data=temp, main="DMS53+SNS-314", type='n')
for(i in id)
{
    dtp <- temp[temp$uid==i,]
    lines(dtp$time,log2(dtp$cell_count))
}
```

```{r}
temp <- d[d$cell.line=="DMS53" & d$drug1=="Barasertib (AZD1152-H",]
id <- unique(temp$uid)
plot(log2(cell.count - ch2_pos) ~ time, data=temp, main="DMS53+Barasertib", type='n')
for(i in id)
{
    dtp <- temp[temp$uid==i,]
    lines(dtp$time,log2(dtp$cell_count-dtp$ch2_pos))
}
```

```{r}
temp <- d[d$cell.line=="NCIH1048" & d$drug1=="Barasertib (AZD1152-H",]
id <- unique(temp$uid)
plot(log2(cell.count - ch2_pos) ~ time, data=temp, main="NCIH1048+Barasertib", type='n')
for(i in id)
{
    dtp <- temp[temp$uid==i,]
    lines(dtp$time,log2(dtp$cell_count-dtp$ch2_pos))
}
```

```{r}
temp <- d[d$cell.line=="NCIH1048" & d$drug1=="Barasertib (AZD1152-H",]
id <- unique(temp$uid)
plot(log2(cell.count) ~ time, data=temp, main="NCIH1048+Barasertib", type='n')
for(i in id)
{
    dtp <- temp[temp$uid==i,]
    lines(dtp$time,log2(dtp$cell_count))
}
```

